echo OFF

:: Grab root path of script working directory
set SCRIPT_ROOT=%CD%

:: Store path to user startup folder
set STARTFOLDER_RELPATH=\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
set STARTFOLDER_FULLPATH="%HOMEDRIVE%%HOMEPATH%%STARTFOLDER_RELPATH%"

:: Store path and filename for startup.bat
set BATCHSCRIPT_RELPATH=\CompStart\
set BATCHSCRIPT_FILENAME=startup.bat
set BATCHSCRIPT_FULLPATH=%SCRIPT_ROOT%%BATCHSCRIPT_RELPATH%%BATCHSCRIPT_FILENAME%
:: NEED TO CHANGE BATCHSCRIPT_FILENAME FROM test.bat TO startup.bat FOR PRODUCTION

:: Store path and filename for startup.ps1
set POWERSHELLSCRIPT_RELPATH=\CompStart\
set POWERSHELLSCRIPT_FILENAME=startup.ps1
set POWERSHELLSCRIPT_FULLPATH=%SCRIPT_ROOT%%POWERSHELLSCRIPT_RELPATH%%POWERSHELLSCRIPT_FILENAME%

:: Store startup command to use when creating startup.bat
set BATCHSCRIPT_CMD=start powershell.exe -ExecutionPolicy Unrestricted -File %POWERSHELLSCRIPT_FULLPATH%

:: Testing to confirm variables are correct
echo SCRIPT_ROOT: %SCRIPT_ROOT%
echo STARTFOLDER_RELPATH: %STARTFOLDER_RELPATH%
echo STARTFOLDER_FULLPATH: %STARTFOLDER_FULLPATH%
echo BATCHSCRIPT_RELPATH: %BATCHSCRIPT_RELPATH%
echo BATCHSCRIPT_FILENAME: %BATCHSCRIPT_FILENAME%
echo BATCHSCRIPT_FULLPATH: %BATCHSCRIPT_FULLPATH%
echo POWERSHELLSCRIPT_RELPATH: %POWERSHELLSCRIPT_RELPATH%
echo POWERSHELLSCRIPT_FILENAME: %POWERSHELLSCRIPT_FILENAME%
echo POWERSHELLSCRIPT_FULLPATH: %POWERSHELLSCRIPT_FULLPATH%
echo BATCHSCRIPT_CMD: %BATCHSCRIPT_CMD%

:: Create startup.bat which will be used to called the startup.ps1 PowerShell script
echo %BATCHSCRIPT_CMD% > %BATCHSCRIPT_FULLPATH%